name: test_frezux
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #infrastructure
  get_it: 7.2.0 
  provider: 6.0.3 

  #UI
  intl: 0.17.0
  cupertino_icons: 1.0.2

  #domain
  money2: 3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: 2.2.4
  flutter_launcher_icons: 0.9.3
  rename: 2.0.1 

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/currencies/
